name: "Test workflow"

on:
  push:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: dsp-testing/robertbrignull-runs-post-test@main
      with:
        sleep-time: 1000
